// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"github.com/adshao/ordinals-indexer/internal/data/ent/collection"
	"github.com/adshao/ordinals-indexer/internal/data/ent/predicate"
	"github.com/adshao/ordinals-indexer/internal/data/ent/token"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// TokenUpdate is the builder for updating Token entities.
type TokenUpdate struct {
	config
	hooks    []Hook
	mutation *TokenMutation
}

// Where appends a list predicates to the TokenUpdate builder.
func (tu *TokenUpdate) Where(ps ...predicate.Token) *TokenUpdate {
	tu.mutation.Where(ps...)
	return tu
}

// SetUpdatedAt sets the "updated_at" field.
func (tu *TokenUpdate) SetUpdatedAt(t time.Time) *TokenUpdate {
	tu.mutation.SetUpdatedAt(t)
	return tu
}

// SetTick sets the "tick" field.
func (tu *TokenUpdate) SetTick(s string) *TokenUpdate {
	tu.mutation.SetTick(s)
	return tu
}

// SetP sets the "p" field.
func (tu *TokenUpdate) SetP(s string) *TokenUpdate {
	tu.mutation.SetP(s)
	return tu
}

// SetNillableP sets the "p" field if the given value is not nil.
func (tu *TokenUpdate) SetNillableP(s *string) *TokenUpdate {
	if s != nil {
		tu.SetP(*s)
	}
	return tu
}

// SetTokenID sets the "token_id" field.
func (tu *TokenUpdate) SetTokenID(u uint64) *TokenUpdate {
	tu.mutation.ResetTokenID()
	tu.mutation.SetTokenID(u)
	return tu
}

// AddTokenID adds u to the "token_id" field.
func (tu *TokenUpdate) AddTokenID(u int64) *TokenUpdate {
	tu.mutation.AddTokenID(u)
	return tu
}

// SetTxHash sets the "tx_hash" field.
func (tu *TokenUpdate) SetTxHash(s string) *TokenUpdate {
	tu.mutation.SetTxHash(s)
	return tu
}

// SetBlockHeight sets the "block_height" field.
func (tu *TokenUpdate) SetBlockHeight(u uint64) *TokenUpdate {
	tu.mutation.ResetBlockHeight()
	tu.mutation.SetBlockHeight(u)
	return tu
}

// AddBlockHeight adds u to the "block_height" field.
func (tu *TokenUpdate) AddBlockHeight(u int64) *TokenUpdate {
	tu.mutation.AddBlockHeight(u)
	return tu
}

// SetBlockTime sets the "block_time" field.
func (tu *TokenUpdate) SetBlockTime(t time.Time) *TokenUpdate {
	tu.mutation.SetBlockTime(t)
	return tu
}

// SetAddress sets the "address" field.
func (tu *TokenUpdate) SetAddress(s string) *TokenUpdate {
	tu.mutation.SetAddress(s)
	return tu
}

// SetInscriptionID sets the "inscription_id" field.
func (tu *TokenUpdate) SetInscriptionID(i int64) *TokenUpdate {
	tu.mutation.ResetInscriptionID()
	tu.mutation.SetInscriptionID(i)
	return tu
}

// AddInscriptionID adds i to the "inscription_id" field.
func (tu *TokenUpdate) AddInscriptionID(i int64) *TokenUpdate {
	tu.mutation.AddInscriptionID(i)
	return tu
}

// SetInscriptionUID sets the "inscription_uid" field.
func (tu *TokenUpdate) SetInscriptionUID(s string) *TokenUpdate {
	tu.mutation.SetInscriptionUID(s)
	return tu
}

// SetCollectionID sets the "collection" edge to the Collection entity by ID.
func (tu *TokenUpdate) SetCollectionID(id int) *TokenUpdate {
	tu.mutation.SetCollectionID(id)
	return tu
}

// SetNillableCollectionID sets the "collection" edge to the Collection entity by ID if the given value is not nil.
func (tu *TokenUpdate) SetNillableCollectionID(id *int) *TokenUpdate {
	if id != nil {
		tu = tu.SetCollectionID(*id)
	}
	return tu
}

// SetCollection sets the "collection" edge to the Collection entity.
func (tu *TokenUpdate) SetCollection(c *Collection) *TokenUpdate {
	return tu.SetCollectionID(c.ID)
}

// Mutation returns the TokenMutation object of the builder.
func (tu *TokenUpdate) Mutation() *TokenMutation {
	return tu.mutation
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (tu *TokenUpdate) ClearCollection() *TokenUpdate {
	tu.mutation.ClearCollection()
	return tu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (tu *TokenUpdate) Save(ctx context.Context) (int, error) {
	tu.defaults()
	return withHooks(ctx, tu.sqlSave, tu.mutation, tu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tu *TokenUpdate) SaveX(ctx context.Context) int {
	affected, err := tu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (tu *TokenUpdate) Exec(ctx context.Context) error {
	_, err := tu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tu *TokenUpdate) ExecX(ctx context.Context) {
	if err := tu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tu *TokenUpdate) defaults() {
	if _, ok := tu.mutation.UpdatedAt(); !ok {
		v := token.UpdateDefaultUpdatedAt()
		tu.mutation.SetUpdatedAt(v)
	}
}

func (tu *TokenUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := sqlgraph.NewUpdateSpec(token.Table, token.Columns, sqlgraph.NewFieldSpec(token.FieldID, field.TypeInt))
	if ps := tu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tu.mutation.UpdatedAt(); ok {
		_spec.SetField(token.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tu.mutation.Tick(); ok {
		_spec.SetField(token.FieldTick, field.TypeString, value)
	}
	if value, ok := tu.mutation.P(); ok {
		_spec.SetField(token.FieldP, field.TypeString, value)
	}
	if value, ok := tu.mutation.TokenID(); ok {
		_spec.SetField(token.FieldTokenID, field.TypeUint64, value)
	}
	if value, ok := tu.mutation.AddedTokenID(); ok {
		_spec.AddField(token.FieldTokenID, field.TypeUint64, value)
	}
	if value, ok := tu.mutation.TxHash(); ok {
		_spec.SetField(token.FieldTxHash, field.TypeString, value)
	}
	if value, ok := tu.mutation.BlockHeight(); ok {
		_spec.SetField(token.FieldBlockHeight, field.TypeUint64, value)
	}
	if value, ok := tu.mutation.AddedBlockHeight(); ok {
		_spec.AddField(token.FieldBlockHeight, field.TypeUint64, value)
	}
	if value, ok := tu.mutation.BlockTime(); ok {
		_spec.SetField(token.FieldBlockTime, field.TypeTime, value)
	}
	if value, ok := tu.mutation.Address(); ok {
		_spec.SetField(token.FieldAddress, field.TypeString, value)
	}
	if value, ok := tu.mutation.InscriptionID(); ok {
		_spec.SetField(token.FieldInscriptionID, field.TypeInt64, value)
	}
	if value, ok := tu.mutation.AddedInscriptionID(); ok {
		_spec.AddField(token.FieldInscriptionID, field.TypeInt64, value)
	}
	if value, ok := tu.mutation.InscriptionUID(); ok {
		_spec.SetField(token.FieldInscriptionUID, field.TypeString, value)
	}
	if tu.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   token.CollectionTable,
			Columns: []string{token.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tu.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   token.CollectionTable,
			Columns: []string{token.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, tu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{token.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	tu.mutation.done = true
	return n, nil
}

// TokenUpdateOne is the builder for updating a single Token entity.
type TokenUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TokenMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (tuo *TokenUpdateOne) SetUpdatedAt(t time.Time) *TokenUpdateOne {
	tuo.mutation.SetUpdatedAt(t)
	return tuo
}

// SetTick sets the "tick" field.
func (tuo *TokenUpdateOne) SetTick(s string) *TokenUpdateOne {
	tuo.mutation.SetTick(s)
	return tuo
}

// SetP sets the "p" field.
func (tuo *TokenUpdateOne) SetP(s string) *TokenUpdateOne {
	tuo.mutation.SetP(s)
	return tuo
}

// SetNillableP sets the "p" field if the given value is not nil.
func (tuo *TokenUpdateOne) SetNillableP(s *string) *TokenUpdateOne {
	if s != nil {
		tuo.SetP(*s)
	}
	return tuo
}

// SetTokenID sets the "token_id" field.
func (tuo *TokenUpdateOne) SetTokenID(u uint64) *TokenUpdateOne {
	tuo.mutation.ResetTokenID()
	tuo.mutation.SetTokenID(u)
	return tuo
}

// AddTokenID adds u to the "token_id" field.
func (tuo *TokenUpdateOne) AddTokenID(u int64) *TokenUpdateOne {
	tuo.mutation.AddTokenID(u)
	return tuo
}

// SetTxHash sets the "tx_hash" field.
func (tuo *TokenUpdateOne) SetTxHash(s string) *TokenUpdateOne {
	tuo.mutation.SetTxHash(s)
	return tuo
}

// SetBlockHeight sets the "block_height" field.
func (tuo *TokenUpdateOne) SetBlockHeight(u uint64) *TokenUpdateOne {
	tuo.mutation.ResetBlockHeight()
	tuo.mutation.SetBlockHeight(u)
	return tuo
}

// AddBlockHeight adds u to the "block_height" field.
func (tuo *TokenUpdateOne) AddBlockHeight(u int64) *TokenUpdateOne {
	tuo.mutation.AddBlockHeight(u)
	return tuo
}

// SetBlockTime sets the "block_time" field.
func (tuo *TokenUpdateOne) SetBlockTime(t time.Time) *TokenUpdateOne {
	tuo.mutation.SetBlockTime(t)
	return tuo
}

// SetAddress sets the "address" field.
func (tuo *TokenUpdateOne) SetAddress(s string) *TokenUpdateOne {
	tuo.mutation.SetAddress(s)
	return tuo
}

// SetInscriptionID sets the "inscription_id" field.
func (tuo *TokenUpdateOne) SetInscriptionID(i int64) *TokenUpdateOne {
	tuo.mutation.ResetInscriptionID()
	tuo.mutation.SetInscriptionID(i)
	return tuo
}

// AddInscriptionID adds i to the "inscription_id" field.
func (tuo *TokenUpdateOne) AddInscriptionID(i int64) *TokenUpdateOne {
	tuo.mutation.AddInscriptionID(i)
	return tuo
}

// SetInscriptionUID sets the "inscription_uid" field.
func (tuo *TokenUpdateOne) SetInscriptionUID(s string) *TokenUpdateOne {
	tuo.mutation.SetInscriptionUID(s)
	return tuo
}

// SetCollectionID sets the "collection" edge to the Collection entity by ID.
func (tuo *TokenUpdateOne) SetCollectionID(id int) *TokenUpdateOne {
	tuo.mutation.SetCollectionID(id)
	return tuo
}

// SetNillableCollectionID sets the "collection" edge to the Collection entity by ID if the given value is not nil.
func (tuo *TokenUpdateOne) SetNillableCollectionID(id *int) *TokenUpdateOne {
	if id != nil {
		tuo = tuo.SetCollectionID(*id)
	}
	return tuo
}

// SetCollection sets the "collection" edge to the Collection entity.
func (tuo *TokenUpdateOne) SetCollection(c *Collection) *TokenUpdateOne {
	return tuo.SetCollectionID(c.ID)
}

// Mutation returns the TokenMutation object of the builder.
func (tuo *TokenUpdateOne) Mutation() *TokenMutation {
	return tuo.mutation
}

// ClearCollection clears the "collection" edge to the Collection entity.
func (tuo *TokenUpdateOne) ClearCollection() *TokenUpdateOne {
	tuo.mutation.ClearCollection()
	return tuo
}

// Where appends a list predicates to the TokenUpdate builder.
func (tuo *TokenUpdateOne) Where(ps ...predicate.Token) *TokenUpdateOne {
	tuo.mutation.Where(ps...)
	return tuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (tuo *TokenUpdateOne) Select(field string, fields ...string) *TokenUpdateOne {
	tuo.fields = append([]string{field}, fields...)
	return tuo
}

// Save executes the query and returns the updated Token entity.
func (tuo *TokenUpdateOne) Save(ctx context.Context) (*Token, error) {
	tuo.defaults()
	return withHooks(ctx, tuo.sqlSave, tuo.mutation, tuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (tuo *TokenUpdateOne) SaveX(ctx context.Context) *Token {
	node, err := tuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (tuo *TokenUpdateOne) Exec(ctx context.Context) error {
	_, err := tuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (tuo *TokenUpdateOne) ExecX(ctx context.Context) {
	if err := tuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (tuo *TokenUpdateOne) defaults() {
	if _, ok := tuo.mutation.UpdatedAt(); !ok {
		v := token.UpdateDefaultUpdatedAt()
		tuo.mutation.SetUpdatedAt(v)
	}
}

func (tuo *TokenUpdateOne) sqlSave(ctx context.Context) (_node *Token, err error) {
	_spec := sqlgraph.NewUpdateSpec(token.Table, token.Columns, sqlgraph.NewFieldSpec(token.FieldID, field.TypeInt))
	id, ok := tuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Token.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := tuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, token.FieldID)
		for _, f := range fields {
			if !token.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != token.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := tuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := tuo.mutation.UpdatedAt(); ok {
		_spec.SetField(token.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.Tick(); ok {
		_spec.SetField(token.FieldTick, field.TypeString, value)
	}
	if value, ok := tuo.mutation.P(); ok {
		_spec.SetField(token.FieldP, field.TypeString, value)
	}
	if value, ok := tuo.mutation.TokenID(); ok {
		_spec.SetField(token.FieldTokenID, field.TypeUint64, value)
	}
	if value, ok := tuo.mutation.AddedTokenID(); ok {
		_spec.AddField(token.FieldTokenID, field.TypeUint64, value)
	}
	if value, ok := tuo.mutation.TxHash(); ok {
		_spec.SetField(token.FieldTxHash, field.TypeString, value)
	}
	if value, ok := tuo.mutation.BlockHeight(); ok {
		_spec.SetField(token.FieldBlockHeight, field.TypeUint64, value)
	}
	if value, ok := tuo.mutation.AddedBlockHeight(); ok {
		_spec.AddField(token.FieldBlockHeight, field.TypeUint64, value)
	}
	if value, ok := tuo.mutation.BlockTime(); ok {
		_spec.SetField(token.FieldBlockTime, field.TypeTime, value)
	}
	if value, ok := tuo.mutation.Address(); ok {
		_spec.SetField(token.FieldAddress, field.TypeString, value)
	}
	if value, ok := tuo.mutation.InscriptionID(); ok {
		_spec.SetField(token.FieldInscriptionID, field.TypeInt64, value)
	}
	if value, ok := tuo.mutation.AddedInscriptionID(); ok {
		_spec.AddField(token.FieldInscriptionID, field.TypeInt64, value)
	}
	if value, ok := tuo.mutation.InscriptionUID(); ok {
		_spec.SetField(token.FieldInscriptionUID, field.TypeString, value)
	}
	if tuo.mutation.CollectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   token.CollectionTable,
			Columns: []string{token.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := tuo.mutation.CollectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   token.CollectionTable,
			Columns: []string{token.CollectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(collection.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Token{config: tuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, tuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{token.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	tuo.mutation.done = true
	return _node, nil
}
