// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Collection is the predicate function for collection builders.
type Collection func(*sql.Selector)

// Inscription is the predicate function for inscription builders.
type Inscription func(*sql.Selector)

// Token is the predicate function for token builders.
type Token func(*sql.Selector)
