-- Create "collections" table
CREATE TABLE "collections" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "tick" character varying NOT NULL, "p" character varying NOT NULL DEFAULT 'brc-721', "max" bigint NOT NULL, "supply" bigint NOT NULL, "base_uri" character varying NOT NULL, "name" character varying NOT NULL, "description" character varying NOT NULL, "image" character varying NOT NULL, "attributes" jsonb NOT NULL, "tx_hash" character varying NOT NULL, "block_height" bigint NOT NULL, "block_time" timestamptz NOT NULL, "address" character varying NOT NULL, "inscription_id" bigint NOT NULL, PRIMARY KEY ("id"));
-- Create index "collection_address" to table: "collections"
CREATE INDEX "collection_address" ON "collections" ("address");
-- Create index "collection_block_height" to table: "collections"
CREATE INDEX "collection_block_height" ON "collections" ("block_height");
-- Create index "collection_inscription_id" to table: "collections"
CREATE INDEX "collection_inscription_id" ON "collections" ("inscription_id");
-- Create index "collection_p_tick" to table: "collections"
CREATE UNIQUE INDEX "collection_p_tick" ON "collections" ("p", "tick");
-- Create index "collection_tx_hash" to table: "collections"
CREATE INDEX "collection_tx_hash" ON "collections" ("tx_hash");
-- Create "tokens" table
CREATE TABLE "tokens" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "tick" character varying NOT NULL, "p" character varying NOT NULL DEFAULT 'brc-721', "token_id" bigint NOT NULL, "tx_hash" character varying NOT NULL, "block_height" bigint NOT NULL, "block_time" timestamptz NOT NULL, "address" character varying NOT NULL, "inscription_id" bigint NOT NULL, "collection_tokens" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "tokens_collections_tokens" FOREIGN KEY ("collection_tokens") REFERENCES "collections" ("id") ON UPDATE NO ACTION ON DELETE SET NULL);
-- Create index "token_address" to table: "tokens"
CREATE INDEX "token_address" ON "tokens" ("address");
-- Create index "token_block_height" to table: "tokens"
CREATE INDEX "token_block_height" ON "tokens" ("block_height");
-- Create index "token_inscription_id" to table: "tokens"
CREATE INDEX "token_inscription_id" ON "tokens" ("inscription_id");
-- Create index "token_p_tick_token_id" to table: "tokens"
CREATE UNIQUE INDEX "token_p_tick_token_id" ON "tokens" ("p", "tick", "token_id");
-- Create index "token_tx_hash" to table: "tokens"
CREATE INDEX "token_tx_hash" ON "tokens" ("tx_hash");
-- Create index "tokens_tick_key" to table: "tokens"
CREATE UNIQUE INDEX "tokens_tick_key" ON "tokens" ("tick");
